version: "3"
services:
  dev-uploader:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      # LOGS in numbers
      - "5647:5000"
    volumes:
      - $PWD:/dev_src
      - ./phonelogs/:/phonelogs
    networks:
       - emission

networks:
  emission:
